## A、NumPy的ndarray:一种多维数组对象

In [2]:
import numpy as np

data = np.random.randn(2, 3)
print(data)
#所有元素都乘以10
print('data * 10: \n', data * 10)

[[ 0.2980714   0.11832336 -0.26738158]
 [ 0.65831546  0.33080115  0.16616952]]
data * 10: 
 [[ 2.98071402  1.1832336  -2.67381584]
 [ 6.58315461  3.30801151  1.66169521]]


### a、创建数组

array:将python对象(list/tuple)转化为数组

In [3]:
list_0 = list(range(4))
list_1 = [list_0] * 2
print(list_1)
arr_0 = np.array(list_1)
print(arr_0)
print(arr_0.ndim)
print(arr_0.shape)

[[0, 1, 2, 3], [0, 1, 2, 3]]
[[0 1 2 3]
 [0 1 2 3]]
2
(2, 4)


np.array会尝试为新建的数组推断出一个较为合适的数据类型，数据类型保存在一个特殊的dtype对象中

In [4]:
list_2 = [1, 3, 1.5]
arr_1 = np.array(list_2)
print(arr_1.dtype)

float64


empty()：分配指定大小的数组，未初始化 ，随机填充值(元组形式输入shape)

In [8]:
print(np.empty((2,2)))

[[1.46987566e-311 4.94065646e-324]
 [0.00000000e+000 0.00000000e+000]]


zeros(), ones()：创建全为0或1的数组

In [9]:
arr_0s = np.zeros((2,3))
arr_1s = np.ones((2,2))
print(arr_0s)
print(arr_1s)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


### b、ndarray的数据类型

ndarry基本数据类型

In [10]:
print(set(np.typeDict.values()))

{<class 'numpy.uint32'>, <class 'numpy.str_'>, <class 'numpy.datetime64'>, <class 'numpy.float32'>, <class 'numpy.bool_'>, <class 'numpy.float64'>, <class 'numpy.clongdouble'>, <class 'numpy.float16'>, <class 'numpy.bytes_'>, <class 'numpy.uint16'>, <class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.timedelta64'>, <class 'numpy.int32'>, <class 'numpy.uint8'>, <class 'numpy.longdouble'>, <class 'numpy.void'>, <class 'numpy.int64'>, <class 'numpy.uintc'>, <class 'numpy.object_'>, <class 'numpy.int8'>, <class 'numpy.intc'>, <class 'numpy.uint64'>, <class 'numpy.int16'>}


指定数据类型--dtype

In [14]:
np.array(range(10),dtype = 'c8')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j], dtype=complex64)

In [15]:
np.array(range(10),dtype = 'f4')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [18]:
np.array(range(255,260), dtype = 'i1')

array([-1,  0,  1,  2,  3], dtype=int8)

In [17]:
np.array(range(255,260), dtype = 'i2')

array([255, 256, 257, 258, 259], dtype=int16)

转换数据类型--arr.astype(dtype)

In [19]:
arr_4 = np.array(range(5))
print(arr_4,arr_4.dtype)
float_arr4 = arr_4.astype('f8')
print(float_arr4,float_arr4.dtype)

[0 1 2 3 4] int32
[0. 1. 2. 3. 4.] float64


将浮点数转换成整数，则小数部分将会被截取删除

In [20]:
arr_5 = arr_4 + arr_4/10
print(arr_5,arr_5.dtype)
int_arr5 = arr_5.astype('i4')
print(int_arr5, int_arr5.dtype)

[0.  1.1 2.2 3.3 4.4] float64
[0 1 2 3 4] int32


如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式

In [21]:
arr_strs = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(arr_strs,arr_strs.dtype)
float_arr_strs = arr_strs.astype(float)
print(float_arr_strs,float_arr_strs.dtype)

[b'1.25' b'-9.6' b'42'] |S4
[ 1.25 -9.6  42.  ] float64


### c、数组形状操作

使用reshape，有返回值

In [22]:
arr_5 = np.array(range(9))
print(arr_5)
reshape_arr5 = arr_5.reshape((3,3))
print(reshape_arr5)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


这里改变arr_5的值，reshape_arr5的值也会跟着变，反过来改变reshape_arr5的值，arr_5同样也跟着变

In [23]:
arr_5[0] = 99
print('arr_5:\n',arr_5)
print('reshape_arr5:\n',reshape_arr5)

arr_5:
 [99  1  2  3  4  5  6  7  8]
reshape_arr5:
 [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


-1代表的维度的取值需要根据数组的长度和其他维度来共同确认

In [24]:
reshape_arr5.reshape((-1,3))

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

shape 数组本身改变

In [25]:
arr_5 = np.array(range(9))
print(arr_5)
arr_5.shape = (3,3)
print(arr_5)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


使用resize，但是没有返回值

In [26]:
arr_5 = np.array(range(9))
print('arr_5:\n',arr_5)
resize_arr5 = arr_5.resize(3,3)
print('resize_arr5:\n',resize_arr5)

arr_5:
 [0 1 2 3 4 5 6 7 8]
resize_arr5:
 None


ravel 扁平化

同样，改变arr_5也会改变revel_arr5，反之亦然

In [28]:
arr_5 = np.array(range(9))
arr_5.shape = (3,3)
print('arr_5:\n',arr_5)
ravel_arr5 = arr_5.ravel()
print('ravel_arr5:\n', ravel_arr5)

arr_5:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
ravel_arr5:
 [0 1 2 3 4 5 6 7 8]


flatten 扁平化

In [30]:
#跟ravel的作用一样，但不同的是新创建出来的数组与原数组改变时，互不影响
flatten_arr5 = arr_5.flatten()

### d、NunPy数组的运算

In [31]:
arr_5 = np.array(range(9))
arr_5.shape = (3,3)
print('arr_5:\n',arr_5)
print('arr_5 * arr_5:\n',arr_5 * arr_5)

arr_5:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_5 * arr_5:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


数组与标量的算术运算会将标量值传播到各个元素 + - * / // % **

In [32]:
arr_5 = np.array(range(9))
arr_5.shape = (3,3)
print('arr_5:\n',arr_5)
print('arr_5+3:\n',arr_5+3)

arr_5:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_5+3:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


shape相同的数组之间的比较会生成布尔值数组

In [33]:
arr_5 = np.array(range(9))
arr_5.shape = (3,3)
print('arr_5:\n',arr_5)
print('arr_5%3:\n',arr_5%3)
print('判断arr_5 == arr_5%3:\n',arr_5 == arr_5%3)

arr_5:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_5%3:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]
判断arr_5 == arr_5%3:
 [[ True  True  True]
 [False False False]
 [False False False]]


### e、数组的广播(broadcast)

In [34]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0],)  
print ('数组a：\n',a)  
print ('数组b：\n',b)  
print ('数组a加数组b：\n',a+b)  

数组a：
 [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
数组b：
 [1. 2. 3.]
数组a加数组b：
 [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


### f、索引和切片

一维数组：类似列表；
跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上

In [35]:
#numpy
arr = np.array(range(10))
arr_slice = arr[3:6]
print('arr:\n',arr)
print('arr_alice:\n',arr_slice)
#列表
ls = list(range(10))
ls_slice = ls[3:6]
print('ls:\n',ls)
print('ls_slice:\n',ls_slice)

arr:
 [0 1 2 3 4 5 6 7 8 9]
arr_alice:
 [3 4 5]
ls:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ls_slice:
 [3, 4, 5]


In [36]:
arr_slice[0]= 12345
ls_slice[0] = 12345
print('arr:\n',arr)
print('arr_alice:\n',arr_slice)
print('ls:\n',ls)
print('ls_slice:\n',ls_slice)

arr:
 [    0     1     2 12345     4     5     6     7     8     9]
arr_alice:
 [12345     4     5]
ls:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ls_slice:
 [12345, 4, 5]


切片[ : ]会给数组中的所有值赋值：

In [37]:
arr_slice[:] = 0
print('arr:\n',arr)
print('arr_alice:\n',arr_slice)

arr:
 [0 1 2 0 0 0 6 7 8 9]
arr_alice:
 [0 0 0]


如果想要得到的是ndarray切片的一份副本，就需要进行复制操作copy()

In [38]:
arr = np.array(range(10))
arr_slice = arr[3:6].copy()
print('arr:\n',arr)
print('arr_alice:\n',arr_slice)
arr_slice[:] = 0
print('arr:\n',arr)
print('arr_alice:\n',arr_slice)

arr:
 [0 1 2 3 4 5 6 7 8 9]
arr_alice:
 [3 4 5]
arr:
 [0 1 2 3 4 5 6 7 8 9]
arr_alice:
 [0 0 0]


高维度数组:索引位置上的元素不再是标量而是一维数组

In [39]:
ls = [list(range(5)),list(range(5,10))]
arr = np.array(ls)
print(arr[0,2:])

[2 3 4]


在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray

In [40]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d.shape
print(arr3d[0])
print(arr3d[0,0])
print(arr3d[0,0,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1


标量值和数组都可以被赋值给数组

In [41]:
#将arr3d[0]的数据进行备份
old_values = arr3d[0].copy()
#修改arr3d[0]的值为42
arr3d[0] = 42
print(arr3d)
print('===========分割线============')
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
===========分割线============
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### g、布尔型索引

In [42]:
strs = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])
data = np.random.randn(7, 4) #随机形成7*4的数组
print(strs)
print(data)

['a' 'b' 'c' 'd' 'e' 'f' 'g']
[[-0.79151121 -0.13016484 -1.0609822   1.16067896]
 [-0.5813913  -2.42177945 -0.2964941   1.7495043 ]
 [ 0.94254716 -0.39216868 -1.69488846  0.04888326]
 [-0.96420395  0.82330884 -1.12783834  0.12025467]
 [ 0.88096024 -0.17940293  0.47441052 -0.25057357]
 [ 0.07643833 -1.20633853 -1.15822811  1.33534246]
 [ 0.40242716  0.36662169  0.05819316 -0.5386873 ]]


假设每个字母都对应data数组中的一行，如何选出对应于字母'a'的所有行？

In [43]:
print(strs == 'a')
print(data[strs == 'a'])
print(data[strs == 'a',2:])

[ True False False False False False False]
[[-0.79151121 -0.13016484 -1.0609822   1.16067896]]
[[-1.0609822   1.16067896]]


要选择'a'以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定

In [44]:
print(strs != 'a')
print(data[~(strs == 'a')])

[False  True  True  True  True  True  True]
[[-0.5813913  -2.42177945 -0.2964941   1.7495043 ]
 [ 0.94254716 -0.39216868 -1.69488846  0.04888326]
 [-0.96420395  0.82330884 -1.12783834  0.12025467]
 [ 0.88096024 -0.17940293  0.47441052 -0.25057357]
 [ 0.07643833 -1.20633853 -1.15822811  1.33534246]
 [ 0.40242716  0.36662169  0.05819316 -0.5386873 ]]


### h、数组转置和轴对换

T:转置/轴反转；transpose：轴对换

In [45]:
arr = np.arange(15).reshape((3, 5))
print('arr:\n',arr)
print('arr.T:\n',arr.T)
#这里transpose实际上是对shape按索引进行一次重新排序
print('arr.transpose((1,0)):\n',arr.transpose((1,0)))

arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr.T:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
arr.transpose((1,0)):
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


在进行矩阵计算时，经常需要用到该操作，比如利用np.dot计算矩阵内积

In [46]:
arr = np.random.randn(6, 3)
print ('arr:\n',arr)
print ('dot_arr:\n',np.dot(arr.T, arr))

arr:
 [[-0.6165663  -0.17301843  1.0565788 ]
 [-0.76286167 -0.31140584  0.04644   ]
 [ 0.45112717 -0.36220175  1.4593615 ]
 [-1.08502013  0.72332201  0.00278254]
 [-0.79758154  1.47005547  0.84725135]
 [-0.20490548  0.41216422 -0.63137637]]
dot_arr:
 [[ 3.02101891 -1.86092489 -0.57791924]
 [-1.86092489  3.11223624  0.26143583]
 [-0.57791924  0.26143583  4.36473015]]


对于高维数组，转置需要得到一个由轴编号组成的元组才能对这些轴进行转置

In [47]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print('========================')
print(arr.transpose((1, 0, 2)))
print('========================')
print('arr_T:\n',arr.T)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
arr_T:
 [[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


## B、通用函数

### b、二元函数

In [48]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [49]:
x = np.random.randn(8)
y = np.random.randn(8)
print('x:\n',x)
print('y:\n',y)
print(np.maximum(x, y))

x:
 [ 1.36682114  1.08955869 -1.33269932  1.24981006  0.43318182 -2.24903016
 -1.40757164  1.17680824]
y:
 [-0.92070236 -1.36113052 -0.31987907 -0.88103292 -0.43373386  0.71688174
 -0.79435769  1.53332102]
[ 1.36682114  1.08955869 -0.31987907  1.24981006  0.43318182  0.71688174
 -0.79435769  1.53332102]


## C、利用数组进行数据处理

想要在一组值（网格型）上计算$sqrt(x^2+y^2)$

In [50]:
points = np.arange(-5, 5, 0.01) 
xs, ys = np.meshgrid(points, points) #生成网格型数据，接受两个一维数组生成两个二维矩阵
print(xs)
print(ys)

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [51]:
z = np.sqrt(xs ** 2 + ys ** 2)
print(z)

[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


### a、将条件逻辑表述为数组运算

numpy.where函数是三元表达式x if condition else y的矢量化版本

In [52]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = []
for x,y,c in zip(xarr,yarr,cond):
    if c:
        result.append(x)
    else:
        result.append(y)
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [53]:
res = np.where(cond, xarr, yarr)
print(res)

[1.1 2.2 1.3 1.4 2.5]


np.where的第二个和第三个参数不必是数组，它们都可以是标量值，在数据分析工作中，where通常用于根据另一个数组而产生一个新的数组

In [54]:
arr = np.random.randn(4, 4)
print(arr)
print(arr > 0)
print(np.where(arr > 0, 'a', -2))

[[-0.23584801 -0.94750973  0.10928306  0.39544099]
 [-0.05203375 -1.20393083 -1.3290124   0.6514226 ]
 [-0.00470393  2.69043775  0.41459335  0.09471023]
 [ 1.00877682 -0.54296457 -1.91897255 -0.26924904]]
[[False False  True  True]
 [False False False  True]
 [False  True  True  True]
 [ True False False False]]
[['-2' '-2' 'a' 'a']
 ['-2' '-2' '-2' 'a']
 ['-2' 'a' 'a' 'a']
 ['a' '-2' '-2' '-2']]


使用np.where，可以将标量和数组结合起来

In [55]:
print(np.where(arr > 0, 2, arr))

[[-0.23584801 -0.94750973  2.          2.        ]
 [-0.05203375 -1.20393083 -1.3290124   2.        ]
 [-0.00470393  2.          2.          2.        ]
 [ 2.         -0.54296457 -1.91897255 -0.26924904]]


### b、数学和统计方法

通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算 求和、平均值、方差、标准差、中位数：sum, mean/average, var, std, median

In [56]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

[[-0.5944898  -2.19389699  0.36065757 -0.3919238 ]
 [ 1.02045986 -1.10730014 -2.26042053 -0.74189185]
 [-0.5604077   1.42969744 -0.36038745 -0.45056563]
 [ 1.6472008  -0.69005456  0.44131405  0.22321446]
 [-0.93162426  0.30508815 -0.91173097  2.18000584]]
-0.17935277544553846
-0.17935277544553846
-3.5870555089107694


axis选项参数，用于计算该轴向上的统计值；
arr.mean(1)是“计算行的平均值”，arr.sum(0)是“计算每列的和”

In [57]:
print(arr.mean(axis=1))
print(arr.sum(axis=0))

[-0.70491326 -0.77228816  0.01458416  0.40541869  0.16043469]
[ 0.5811389  -2.2564661  -2.73056733  0.81883902]


统计>0的数目

In [58]:
arr = np.random.randn(10)
print(arr)
print((arr > 0).sum())

[-0.3536583  -0.35146388 -0.17161577  0.10993688  1.31163529 -0.19996976
 -1.00517353 -0.41450994  0.37008916  3.58555386]
4


### c、排序

numpy.sort() 
sort(a, axis=-1, kind=None, order=None) Return a sorted copy of an array.

In [59]:
a = np.array([[3,7],[9,1]])  
print ('a:\n',a)  
print('*********')
print (np.sort(a))  
print ('*********')   
print (np.sort(a, axis =  0))  
print ('**********')  

dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('a:\n',a) 
print('***********')
print (np.sort(a, order =  'age'))

a:
 [[3 7]
 [9 1]]
*********
[[3 7]
 [1 9]]
*********
[[3 1]
 [9 7]]
**********
a:
 [(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
***********
[(b'ravi', 17) (b'raju', 21) (b'anil', 25) (b'amar', 27)]


numpy.argsort()，返回数据的索引数组

In [60]:
arr = np.random.randn(5, 3)
print(arr)
print('***********')
arr.sort(1)
print(arr)

[[ 1.63515779  1.32208129 -1.79711713]
 [-1.13692836 -0.3961067   0.90571696]
 [ 1.4191196   0.14644551 -2.11262576]
 [-0.41075034  0.27436949  0.75372514]
 [ 0.91990093 -0.31968367  0.12835899]]
***********
[[-1.79711713  1.32208129  1.63515779]
 [-1.13692836 -0.3961067   0.90571696]
 [-2.11262576  0.14644551  1.4191196 ]
 [-0.41075034  0.27436949  0.75372514]
 [-0.31968367  0.12835899  0.91990093]]


In [61]:
arr = np.random.randn(5, 3)
print(arr)
print('***********')
arr.argsort(1)

[[-0.83525328 -1.04769271 -0.98462664]
 [-0.34232608  1.24136219 -0.62242972]
 [ 0.39965773 -0.17980487 -2.95466246]
 [ 0.71945914  0.31764147  0.01902174]
 [-0.67832452 -1.51090291  0.71032102]]
***********


array([[1, 2, 0],
       [2, 0, 1],
       [2, 1, 0],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

## D、伪随机数生成

生成标准正态分布

In [62]:
samples = np.random.normal(size=(4, 4))
print(samples)

[[ 7.47027878e-01 -1.46209233e+00 -4.86176124e-01  1.70507324e-01]
 [-1.08210503e+00  8.77217299e-02  2.49710420e-02  6.20504732e-01]
 [ 1.34422159e+00  7.10407643e-01  3.07375476e-01 -1.10634373e+00]
 [ 9.58361158e-02  9.42660516e-04 -6.17090610e-01 -1.78204763e+00]]


python randam模块一次生成一个样本

In [63]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

676 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
24.9 ms ± 91.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
